version: "3.9"
services:
  leaf-server:
    image: alan10607/leaf
    container_name: leaf-server
    ports:
      - "8081:8080"
    volumes:
      - "~/docker/volume/leaf/log:/log"
    environment:
      - LOG_PATH=/log
      - MYSQL_HOST=leaf-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=leaf-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=root
    depends_on:
      - leaf-mysql
      - leaf-redis
    networks:
      - proxy
    command: ["/wait-for-it.sh", "leaf-mysql:3306", "--", "/wait-for-it.sh", "leaf-redis:6379", "--", "java","-jar","/leaf-server.jar"]

  leaf-mysql:
    image: mysql:8.0.30
    container_name: leaf-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=leaf
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - proxy

  leaf-redis:
    image: redis:7.0.4
    container_name: leaf-redis
    ports:
      - "6380:6379"
    volumes:
      - "~/docker/volume/redis/data:/data"
      - "~/docker/volume/redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "~/docker/volume/redis/logs:/logs"
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes --requirepass "root"
    networks:
      - proxy

networks:
  proxy:
    name: leaf-network
